name: Deploy consul
on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        type: environment
        description: Choose the environment to deploy
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04

    environment:
      name: ${{ inputs.deploy_environment }}

    env:
      SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_CONSUL_STAGING_KEY }}
      SSH_PUBLIC_KEY: ${{ vars.PUBLIC_SERVER_KEY }}
      HOST: ${{ vars.REMOTE_IP }}
      USER: ${{ vars.ANSIBLE_USER }}
      ANSIBLE_USER: ${{ vars.ANSIBLE_USER }}
      DOMAIN: ${{ vars.PRODUCTION_DOMAIN }}
      CONTACT_EMAIL: ${{ vars.CONTACT_EMAIL }}
      INSTALLER_REPO: ${{ vars.INSTALLER_REPO }}
      branch: main

    steps:
      - uses: actions/checkout@v2

      - name: Set REPO variable
        shell: bash
        run: echo "REPO=$(echo ${{ github.repositoryUrl }} | sed "s/git:/https:/")" >> $GITHUB_ENV

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.6"
      - name: Install dependencies
        run: bundle install

      - name: Apply current tenant
        working-directory: .
        run: bin/tenant -a ${{ inputs.deploy_environment }}

      - name: Create deploy secrets
        working-directory: ./config
        run: >-
          sed -e "s/xxx.xxx.xxx.xxx/$HOST/" -e "s/user: "deploy"/user: "$ANSIBLE_USER"/" deploy-secrets.yml.example > deploy-secrets.yml

      - name: Setup SSH
        run: ./init/setupSSH.sh
        working-directory: ${{ github.workspace }}/.github/scripts
        shell: bash

      - name: Run deploy
        working-directory: .
        run: cap production deploy