name: Init new consul
on:
  workflow_dispatch:
    inputs:
      target_environment:
        type: environment
        description: Choose the environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment:
      name: ${{ inputs.target_environment }}

    steps:
      - name: Setup SSH
        run: ./setupSSH.sh
        shell: bash
        working_directory: .github/scripts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_CONSUL_STAGING_KEY }}
          SSH_PUBLIC_KEY: ${{ vars.PUBLIC_SERVER_KEY }}

      - name: Prepare Remote
        run: ./prepareRemote.sh
        working_directory: .github/scripts
        shell: bash

      - name: Execute installer
        run: ./executeInstaller.sh
        shell: bash
        working_directory: .github/scripts
        env:
          HOST: ${{ vars.REMOTE_IP }}
          ANSIBLE_USER: ${{ vars.ANSIBLE_USER }}
          DOMAIN: ${{ vars.PRODUCTION_DOMAIN }}
          CONTACT_EMAIL: ${{ vars.CONTACT_EMAIL }}