name: Init new consul
on:
  workflow_dispatch:
    inputs:
      target_environment:
        type: environment
        description: Choose the environment
        required: true

jobs:
  init:
    runs-on: ubuntu-20.04

    env:
      SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_CONSUL_STAGING_KEY }}
      SSH_PUBLIC_KEY: ${{ vars.PUBLIC_SERVER_KEY }}
      HOST: ${{ vars.REMOTE_IP }}
      USER: ${{ vars.ANSIBLE_USER }}
      ANSIBLE_USER: ${{ vars.ANSIBLE_USER }}
      DOMAIN: ${{ vars.PRODUCTION_DOMAIN }}
      CONTACT_EMAIL: ${{ vars.CONTACT_EMAIL }}
      INSTALLER_REPO: ${{ vars.INSTALLER_REPO }}

    defaults:
      run:
        working-directory: ${{ github.workspace }}/.github/scripts

    environment:
      name: ${{ inputs.target_environment }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        run: ./init/setupSSH.sh
        shell: bash

      - name: Prepare Remote
        run: ./init/prepareRemote.sh
        shell: bash

      - name: Execute installer
        run: ./init/executeInstaller.sh
        shell: bash